name: payments
version: "1.0.0"
profile: payments

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  payments:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table

seeds:
  payments:
    fx_rates:
      +column_types:
        currency: varchar
        rate_to_cad: decimal(12,6)
