kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: payments
nodes:
  - role: control-plane
    extraPortMappings:
      - {containerPort: 30080, hostPort: 8091}  # 8080 is a local Apache, 8090 the host-run scorer
  - role: worker
  - role: worker
